language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
services:
- elasticsearch
- mongodb
install:
- pip install pep8
- pip install pyflakes
- pip install coveralls
- pip install jsonpickle
- pip install pymongo elasticsearch
- pip freeze
- python setup.py install
before_script:
- pyflakes libnessus/*.py
- sleep 10
script: nosetests --with-coverage --cover-package=libnessus
after_script:
- curl -XDELETE localhost:9200/nessus_reports
after_success: coveralls
deploy:
  provider: pypi
  user: Michael.Boutillier
  password:
    secure: JEF0cfTS2uJyN4RhldEJ5fRClhVcCpKSCdg1yTWMIHS6HOuStVyZv/fojAWUP1T95P0JxK1Kfkxwzf7WWaBEHGPlnmjTPa7Db2HuSNq/U68MJ9zIFnbpdqZOEMiiAg67avBJaOAKZSsbcSWJbKYOLT8rCJHlGsd5Djoq9zlugAA=
  on:
    tags: true
    repo: bmx0r/python-libnessus
