language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
services:
- elasticsearch
- mongodb
install:
- pip install pep8
- pip install pyflakes
- pip install coveralls
- pip install jsonpickle
- pip install pymongo elasticsearch
- pip freeze
- python setup.py install
before_script:
- pyflakes libnessus/*.py
- sleep 10
script: nosetests --with-coverage --cover-package=libnessus
after_script:
- curl -XDELETE localhost:9200/nessus_reports
after_success: coveralls
deploy:
  provider: pypi
  user: Michael.Boutillier
  password:
    secure: ir35LrFrBKAbWGJcH+nFmrGP3GS1Bwwwyt2DJqNvWRm1RV6qf7FbpozBfxD2NEGwYFJHjWEODxk8hXcYACidiE01bIPJBJp+MrMob9DUhF9HMAKTnPTmr71L0kNoMI6J2L1rzVIegGidJBoqDZspi1n6nYDtT2n+LfPSYxr/p7o=
  on:
    tags: true
    repo: bmx0r/python-libnessus
